Repository test-fullautomation/robotframework-doip, pull requests merged in 2024-01, with the labels that each got.

#7 Mar3hc/implement doip
  README.md
  README.rst
  packagedoc/additional_docs/History.tex
  packagedoc/additional_docs/The ECU simulator.tex
  packagedoc/packagedoc_config.json
  test/doip-simulation/ecu_factory.py
  test/doip-simulation/ecu_simulator.py
  test/doip-simulation/test_ecu_simulator.py
Labels: enhancement, 0.11.0

#8 Implement feature to trigger AIO workflow.
  .github/workflows/trigger_aio.yml
Labels: enhancement, 0.10.0

#9 Update the tex file in packagedoc_config.json to case sensitive with the tex file
  packagedoc/additional_docs/TheEcuSimulator.tex
  packagedoc/packagedoc_config.json
Labels: enhancement, 0.10.0

#10 Upload document for investigation related to UDS.
  analysis/UDS_Investigation.pptx
Labels: documentation, 0.10.0

#12 Implement the format of input data for diagnostic message.
  README.md
  README.rst
  RobotFramework_DoIP/DoipKeywords.py
  RobotFramework_DoIP/RobotFramework_DoIP.pdf
  RobotFramework_DoIP/__init__.py
  atest/test_connection.robot
  atest/test_diagnostic_msg.robot
  atest/test_interaction.robot
  config/robotframework_aio/release_items_RobotFramework_DoIP.json
Labels: enhancement, 0.10.0

#13 Raise exception for diagnostic methods
  RobotFramework_DoIP/DoipKeywords.py
  RobotFramework_DoIP/RobotFramework_DoIP.pdf
  atest/test_connection.robot
  atest/test_diagnostic_msg.robot
  config/robotframework_aio/release_items_RobotFramework_DoIP.json
Labels: enhancement, 0.10.0

#14 Update the tidy issue related to release info and logger.
  RobotFramework_DoIP/DoipKeywords.py
  RobotFramework_DoIP/RobotFramework_DoIP.pdf
  config/robotframework_aio/release_items_RobotFramework_DoIP.json
Labels: 0.10.0

#15 Layout adaption in release items file
  config/robotframework_aio/release_items_RobotFramework_DoIP.json
Labels: documentation, 0.10.0
